### ISSUE TITLE
Cannot read property 'length' of undefined     at L1ProviderWrapper.getStateRootBatchProof 

### ISSUE THREAD

**Issue by ligi** [ethereum-optimism/verifier#18]
seeing this repeating over and over in the log:

```
[Fraud Prover] [INFO]: Checking state root for mismatch: 0
[Fraud Prover] [INFO]: State roots don't match 𐄂
[Fraud Prover] [INFO]: L1 State Root: 0x5c4954dc33ac95915b41829cf008d02cafae661801c02d5bcaef6d1dc0b2da36
[Fraud Prover] [INFO]: L2 State Root: 0xc645f9c6c4741d70d43f6462969766aa5664407ea118f790e2723083a03dfb52
[Fraud Prover] [INFO]: Found a mismatched state root at index: 0
[Fraud Prover] [INFO]: Pulling fraud proof data...
[Fraud Prover] [INFO]: Getting pre-state root inclusion proof...
[Fraud Prover] [ERROR]: Caught an unhandled error, see error log below:

TypeError: Cannot read property 'length' of undefined
    at L1ProviderWrapper.getStateRootBatchProof (/opt/optimism-ts-services/build/utils/providers/l1-provider-wrapper.js:72:72)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FraudProverService._getFraudProofData (/opt/optimism-ts-services/build/services/fraud-prover.service.js:264:35)
    at async FraudProverService._start (/opt/optimism-ts-services/build/services/fraud-prover.service.js:120:31)
    at async FraudProverService.start (/opt/optimism-ts-services/build/services/base.service.js:36:9)
    at async main (/opt/optimism-ts-services/build/exec/run-fraud-prover.js:34:5)
    at async /opt/optimism-ts-services/exec/run-fraud-prover.js:6:3

```

**Comment by tynes** [comment]
Thank you for reporting this issue. The codebase that has this problem can be found here: https://github.com/ethereum-optimism/optimism-ts-services

There have been a bunch of fixes to that repo so I am unsure if the problem still exists. Will be on the lookout for it

**Comment by ligi** [comment]
thanks! feel free to move the issue to https://github.com/ethereum-optimism/optimism-ts-services
